language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

script:
  ./gradlew build test

jdk:
  - oraclejdk8

sudo: false

before_install:
  - yes | sdkmanager "platforms;android-29"

cache:
  directories:
    - $HOME/.m2
